// UPSCodeToUSPSCountry.cpp
//
// Copyright (C) 2003, 2004, 2005 Matthew Flood
// See file AUTHORS for contact information
//
// This file is part of RudeShipping.
//
// RudeShipping is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2, or (at your option)
// any later version.
// 
// RudeShipping is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with RudeShipping; (see COPYING) if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
// 02111-1307, USA.
//------------------------------------------------------------------------


#include "UPSCodeToUSPSCountry.h"
#include <string.h>

using namespace std;

namespace rude{

namespace shipping{

const char *UPSCodeToUSPSCountry::themap[][2] =
{
	{"AL", "Albania"},
	{"DZ", "Algeria"},
	{"AS", "US Possession"},
	{"AD", "Andorra"},
	{"AO", "Angola"},
	{"AI", "Anguilla"},
	{"AG", "Antigua and Barbuda"},
	{"AR", "Argentina"},
	{"AM", "Armenia"},
	{"AW", "Aruba"},
	{"AU", "Australia"},
	{"AT", "Austria"},
	{"AZ", "Azerbaijan"},
	{"AP", "Azores"},
	{"BS", "Bahamas"},
	{"BH", "Bahrain"},
	{"BD", "Bangladesh"},
	{"BB", "Barbados"},
	{"BY", "Belarus"},
	{"BE", "Belgium"},
	{"BZ", "Belize"},
	{"BJ", "Benin"},
	{"BM", "Bermuda"},
	{"BT", "Bhutan"},
	{"BO", "Bolivia"},
	{"BL", "Netherlands Antilles"},
	{"BA", "Bosnia-Herzegovina"},
	{"BW", "Botswana"},
	{"BV", "Bouvet Island"},
	{"BR", "Brazil"},
	{"IO", "British Indian Ocean Territory"},
	{"BN", "Brunei Darussalam"},
	{"BG", "Bulgaria"},
	{"BF", "Burkina Faso"},
	{"BI", "Burundi"},
	{"KH", "Cambodia"},
	{"CM", "Cameroon"},
	{"CA", "Canada"},
	{"IC", "Spain"},
	{"CV", "Cape Verde"},
	{"KY", "Cayman Islands"},
	{"CF", "Central African Republic"},
	{"TD", "Chad"},
	{"CD", "Great Britain and Northern Ireland"},
	{"CL", "Chile"},
	{"CN", "China"},
	{"CX", "Australia"},
	{"CC", "Australia"},
	{"CO", "Colombia"},
	{"KM", "Comoros"},
	{"ZP", "Congo, Democratic Republic of the"},
	{"CK", "New Zealand"},
	{"CR", "Costa Rica"},
	{"CI", "Cote d lvoire (Ivory Coast)"},
	{"HR", "Croatia"},
	{"CB", "Netherlands Antilles"},
	{"CY", "Cyprus"},
	{"CZ", "Czech Republic"},
	{"DK", "Denmark"},
	{"DJ", "Djibouti"},
	{"DM", "Dominica"},
	{"DO", "Dominican Republic"},
	{"TP", "Indonesia"},
	{"EC", "Ecuador"},
	{"EG", "Egypt"},
	{"SV", "El Salvador"},
	{"EN", "Great Britain and Northern Ireland"},
	{"GQ", "Equatorial Guinea"},
	{"ER", "Eritrea"},
	{"EE", "Estonia"},
	{"ET", "Ethiopia"},
	{"FO", "Faeroe Islands"},
	{"FK", "Falkland Islands"},
	{"FJ", "Fiji"},
	{"FI", "Finland"},
	{"FR", "France"},
	{"GF", "French Guiana"},
	{"PF", "French Polynesia"},
	{"TF", "French Southern Territories"},
	{"GA", "Gabon"},
	{"GM", "Gambia"},
	{"GE", "Georgia, Republic of"},
	{"DE", "Germany"},
	{"GH", "Ghana"},
	{"GI", "Gibraltar"},
	{"GB", "Great Britain and Northern Ireland"},
	{"GR", "Greece"},
	{"GL", "Greenland"},
	{"GD", "Grenada"},
	{"GP", "Guadeloupe"},
	{"GU", "US Possession"},
	{"GT", "Guatemala"},
	{"GN", "Guinea"},
	{"GW", "Guinea-Bissau"},
	{"GY", "Guyana"},
	{"HT", "Haiti"},
	{"HM", "Heard Island and McDonald Islands"},
	{"HN", "Honduras"},
	{"HK", "Hong Kong"},
	{"HU", "Hungary"},
	{"IS", "Iceland"},
	{"IN", "India"},
	{"ID", "Indonesia"},
	{"IE", "Ireland"},
	{"IL", "Israel"},
	{"IT", "Italy"},
	{"JM", "Jamaica"},
	{"JP", "Japan"},
	{"JO", "Jordan"},
	{"KZ", "Kazakhstan"},
	{"KE", "Kenya"},
	{"KI", "Kiribati"},
	{"KO", "US Possession"},
	{"KW", "Kuwait"},
	{"KG", "Kyrgyzstan"},
	{"LA", "Laos"},
	{"LV", "Latvia"},
	{"LB", "Lebanon"},
	{"LS", "Lesotho"},
	{"LR", "Liberia"},
	{"LY", "Libya"},
	{"LI", "Liechtenstein"},
	{"LT", "Lithuania"},
	{"LU", "Luxembourg"},
	{"MO", "Macao"},
	{"MK", "Macedonia, Republic of"},
	{"MG", "Madagascar"},
	{"ME", "Portugal"},
	{"MW", "Malawi"},
	{"MY", "Malaysia"},
	{"MV", "Maldives"},
	{"ML", "Mali"},
	{"MT", "Malta"},
	{"MH", "US Possession"},
	{"MQ", "Martinique"},
	{"MR", "Mauritania"},
	{"MU", "Mauritius"},
	{"YT", "France"},
	{"MX", "Mexico"},
	{"FM", "US Possession"},
	{"MD", "Moldova"},
	{"MC", "France"},
	{"MN", "Mongolia"},
	{"MS", "Montserrat"},
	{"MA", "Morocco"},
	{"MZ", "Mozambique"},
	{"MM", "Burma"},
	{"NA", "Namibia"},
	{"NR", "Nauru"},
	{"NP", "Nepal"},
	{"NL", "Netherlands"},
	{"AN", "Netherlands Antilles"},
	{"NT", "Neutral Zone"},
	{"NC", "New Caledonia"},
	{"NZ", "New Zealand"},
	{"NI", "Nicaragua"},
	{"NE", "Niger"},
	{"NG", "Nigeria"},
	{"NU", "New Zealand"},
	{"NF", "Australia"},
	{"KP", "Korea, Democratic Peoples Republic of (North Korea)"},
	{"NB", "Great Britain and Northern Ireland"},
	{"MP", "US Possession"},
	{"NO", "Norway"},
	{"OM", "Oman"},
	{"PK", "Pakistan"},
	{"PW", "US Possession"},
	{"PA", "Panama"},
	{"PG", "Papua New Guinea"},
	{"PY", "Paraguay"},
	{"PE", "Peru"},
	{"PH", "Philippines"},
	{"PN", "Pitcairn Island"},
	{"PL", "Poland"},
	{"PO", "Ponape"},
	{"PT", "Portugal"},
	{"PR", "US Possession"},
	{"QA", "Qatar"},
	{"RE", "Reunion"},
	{"RO", "Romania"},
	{"RT", "US Possession"},
	{"RU", "Russia"},
	{"RW", "Rwanda"},
	{"SS", "Netherlands Antilles "},
	{"KN", "St. Christopher and Nevis"},
	{"LC", "St. Lucia"},
	{"VC", "St. Vincent and the Grenadines"},
	{"SP", "US Possession"},
	{"WS", "Western Samoa"},
	{"SM", "San Marino"},
	{"ST", "Sao Tome and Principe"},
	{"SA", "Saudi Arabia"},
	{"SF", "Great Britain and Northern Ireland"},
	{"SN", "Senegal"},
	{"SC", "Seychelles"},
	{"SL", "Sierra Leone"},
	{"SG", "Singapore"},
	{"SK", "Slovak Republic"},
	{"SI", "Slovenia"},
	{"SB", "Solomon Islands"},
	{"SO", "Somalia"},
	{"ZA", "South Africa"},
	{"GS", "Falkland Islands"},
	{"KR", "Korea, Republic of (South Korea)"},
	{"ES", "Spain"},
	{"LK", "Sri Lanka"},
	{"NT", "Guadeloupe"},
	{"SW", "St. Christopher and Nevis"},
	{"VI", "US Possession"},
	{"EU", "Netherlands Antilles"},
	{"SH", "St. Helena"},
	{"UV", "US Possession"},
	{"KN", "St. Christopher and Nevis"},
	{"LC", "St. Lucia"},
	{"MB", "Netherlands Antilles"},
	{"TB", "Guadeloupe"},
	{"PM", "St. Pierre and Miquelon"},
	{"VL", "US Possession"},
	{"VC", "St. Vincent and the Grenadines"},
	{"SD", "Sudan"},
	{"SR", "Suriname"},
	{"SJ", "Svalbard and Jan Mayen Islands"},
	{"SZ", "Swaziland"},
	{"SE", "Sweden"},
	{"CH", "Switzerland"},
	{"SY", "Syria"},
	{"TA", "French Polynesia"},
	{"TW", "Taiwan"},
	{"TJ", "Tajikistan"},
	{"TZ", "Tanzania"},
	{"TH", "Thailand"},
	{"TI", "US Possession"},
	{"TG", "Togo"},
	{"TK", "Western Samoa"},
	{"TO", "Tonga"},
	{"TL", "Tortola"},
	{"TT", "Trinidad and Tobago"},
	{"TU", "US Possession "},
	{"TN", "Tunisia"},
	{"TR", "Turkey"},
	{"TM", "Turkmenistan"},
	{"TC", "Turks and Caicos Islands"},
	{"TV", "Tuvalu"},
	{"UG", "Uganda"},
	{"UA", "Ukraine"},
	{"UI", "Union Island"},
	{"AE", "United Arab Emirates"},
	{"US", "United States"},
	{"UY", "Uruguay"},
	{"UM", "US Possession"},
	{"SU", "Russia"},
	{"UZ", "Uzbekistan"},
	{"VU", "Vanuatu"},
	{"VA", "Vatican City"},
	{"VE", "Venezuela"},
	{"VN", "Vietnam"},
	{"VR", "US Possession"},
	{"VG", "British Virgin Islands"},
	{"VI", "US Possession"},
	{"WL", "Great Britain and Northern Ireland"},
	{"WF", "Wallis and Futuna Islands"},
	{"WS", "Western Samoa"},
	{"YA", "US Possession "},
	{"YE", "Yemen"},
	{"YU", "Serbia-Montenegro"},
	{"ZR", "Congo, Democratic Republic of the"},
	{"ZM", "Zambia"},
	{"ZW", "Zimbabwe"},
	{0,0}
	};



const char * UPSCodeToUSPSCountry::getUSPSCountry(const char *UPSCountryCode)
{

	int x=0;
	while(themap[x] != 0)
	{
		if(strcmp(UPSCountryCode, themap[x][0]) == 0)
		{
			return themap[x][1];
		}
		x++;
	}
	return "";
}


}}



